# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: k8s-hatchery

steps:

- script: |
    az version
  displayName: "Get az version"

- task: AzureCLI@2
  displayName: Build and push docker image'
  inputs:
    azureSubscription: TriznaRG-ACR-service-connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      cd ./uni-academy
      az acr login --name triznaacr
      docker build -t uni-academy .
      docker tag uni-academy triznaacr.azurecr.io/uni-academy:v1
      docker push triznaacr.azurecr.io/uni-academy:v1