# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: k8s-hatchery

steps:

- script: |
    cd ./uni-academy
    ls -la
  displayName: 'Move to working directory'

- script: |
    npm version
  displayName: 'Get npm version'

- script: |
    cd ./uni-academy
    npm install
    npm run build
  displayName: 'Build application'

- script: |
    cd ./uni-academy
    docker build -t uni-academy .
    docker tag uni-academy triznaacr.azurecr.io/uni-academy:v1
    az acr login --name triznaacr
    docker push triznaacr.azurecr.io/uni-academy:v1
  displayName: 'Build and push docker image'
